sudo: required
dist: trusty
language: generic

compiler:
  - gcc

notifications:
  email:
    on_failure: always
    recipients:
     - g.a.vanderhoorn@tudelft.nl

env:
  matrix:
    - USE_DEB=true
      ROS_DISTRO="indigo"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true
      ROS_DISTRO="indigo"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
