# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.4434
    has_acceleration_limits: true
    max_acceleration: 0.4886
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.6179
    has_acceleration_limits: true
    max_acceleration: 0.5235
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.7925
    has_acceleration_limits: true
    max_acceleration: 0.5585
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: true
    max_acceleration: 1.3962
  joint_5:
    has_velocity_limits: true
    max_velocity: 5.7595
    has_acceleration_limits: true
    max_acceleration: 1.1519
  joint_6:
    has_velocity_limits: true
    max_velocity: 8.3775
    has_acceleration_limits: true
    max_acceleration: 1.6755
