kinematics_solver_geometric_parameters:
  a1: 0.15
  a2: -0.20
  b: 0.0
  c1: 0.45
  c2: 0.60
  c3: 0.86
  c4: 0.10
kinematics_solver_joint_offsets: [0.0, 0.0, -1.57079632679, 0.0, 0.0, 3.14159265359]
kinematics_solver_joint_sign_corrections: [1, 1, -1, -1, -1, -1]
