joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 6.1087
    has_acceleration_limits: true
    max_acceleration: 1.22174
  joint_2:
    has_velocity_limits: true
    max_velocity: 6.1087
    has_acceleration_limits: true
    max_acceleration: 1.22174
  joint_3:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: true
    max_acceleration: 1.39626
  joint_4:
    has_velocity_limits: true
    max_velocity: 7.854
    has_acceleration_limits: true
    max_acceleration: 1.5708
  joint_5:
    has_velocity_limits: true
    max_velocity: 12.5664
    has_acceleration_limits: true
    max_acceleration: 2.51328
